CC = g++
OPTS = -I../../include -L../../lib
LIBS = -lcapd
PROGS = floatMatrixAlgExample

all: ${PROGS}

floatMatrixAlgExample: floatMatrixAlgExample.cpp
	${CC} ${OPTS} floatMatrixAlgExample.cpp -o floatMatrixAlgExample ${LIBS}
