#!/usr/bin/perl

$prefix = '/usr/local';

@graphicsOptions = (
      'X11 based graphics under linux',
      'wxWidgets based graphics'
    );
@graphicsFlags = (
      '-ansi -pedantic',
      '`wx-config --cxxflags`'
    );
@graphicsLibs = (
      '-L/usr/X11R6/lib64 -L/usr/X11R6/lib -lX11',
      '`wx-config --libs --gl_libs`'
    );

@multiprecisionOptions = (
      'double precision',
      'double precision and multiprecision (gmp and mpfr packages must be installed)'
    );
@multiprecisionFlags = (
      '',
      '-D__HAVE_MPFR__'
    );
@multiprecisionLibs = (
      '',
      '-lmpcapd -lmpfr -lgmp'
    );

@filibOptions = (
      'CAPD implementation of interval arithemtics',
      'FILIB implementation of interval arithemtics'
    );
@filibFlags = (
      '',
      '-D__USE_FILIB__'
    );
@filibLibs = (
      '',
      '-lprim'
    );

print "Installation of the CAPD library.\n\n";

$graphicsSelection = selectOption(@graphicsOptions)-1;
$multiprecisionSelection = selectOption(@multiprecisionOptions)-1;
$filibSelection = selectOption(@filibOptions)-1;

print "Select instalation directory (must exist). Default is /usr/local.:\n";

# now we compile the library with selected configuration
# create a new file 'default' in make/config
open (CONFIG, ">./make/config/default") or die 'Cannot create file make/config/default';

print CONFIG "
SYSLIB  = -lpthread $multiprecisionLibs[$multiprecisionSelection] $filibLibs[$filibSelection]
SYSLIBG = -lpthread $graphicsLibs[$graphicsSelection] $multiprecisionLibs[$multiprecisionSelection] $filibLibs[$filibSelection]
SYSINCL =
COMPILE = g++ -O2 -Wall -frounding-math $graphicsFlags[$graphicsSelection] $multiprecisionFlags[$multiprecisionSelection] $filibFlags[$filibSelection]
LINK    = g++ -s
LINKGUI = g++ -s
MAKELIB = ar cru
IDXLIB  = ranlib
REMOVE  = rm -f
MKDIR   = mkdir
EXE     =
LIBEXT  = .a
OBJEXT  = .o
INSTALLDIR = $prefix
";

close(CONFIG);

# -------------- installation -----------------

# generate scripts for compilation of the CAPD with user's programs
open(CAPDFLAGS,'>capd-flags') or die  "Cannot create capd-flags";
print CAPDFLAGS "echo -Wall -frounding-math -I$prefix/include $graphicsFlags[$graphicsSelection] $multiprecisionFlags[$multiprecisionSelection] $filibFlags[$filibSelection]";
close(CAPDFLAGS);

open(CAPDLIBS,'>capd-libs')  or die  "Cannot create capd-libs";
print CAPDLIBS "echo -lpthread -L$prefix/lib -lcapd $graphicsLibs[$graphicsSelection] $multiprecisionLibs[$multiprecisionSelection] $filibLibs[$filibSelection]";
close(CAPDLIBS);

# copying config files to $prefix/bin location
$built = 'make target=default;';
if($multiprecisionSelection==1)
{
  $built = $built.' make target=default mpcapdlib;' ;
}

exec("
$built
rm -fR $prefix/include/capd;
mkdir $prefix/include/capd;
cp -R ./include/capd $prefix/include;
cp ./lib/lib*capd.a $prefix/lib;
cp ./capd-* $prefix/bin;
chmod 755 $prefix/bin/capd-*;
chmod 755 $prefix/include/capd -R;
chmod 755 $prefix/lib/lib*capd.a
"
);
exit(0);

sub selectOption
{
  print "Select your choice:\n";
  for($i=0;$i<=$#_;$i++)
  {
    $j = $i+1;
    print "$j. $_[$i]\n"
  }

  my $answer;
  do
  {
    $answer = <STDIN>;
  }while($answer<1 or $answer > $#_+1);
  return $answer;
}
