


#IntervalTests contains all tests of Interval Class Template of CAPD Library - threre are many of test fixtured classes
TESTS = IntervalTest

# variable TEST_FIXTURED_CLASSES contains all object files that contain tests
# remember to update this variable, when adding new classes
TEST_FIXTURED_CLASSES = DoubleIntervalTest.o  DIntervalTest.o DoubleRoundingTest.o

# additional libraries used in tests 
LIBRARIES = -lX11 -lmpfr -lgmp

include ../makeTest