Name: ${PACKAGE_NAME}
Description: ${PROJECT_DESCRIPTION}
Version: ${PACKAGE_VERSION}

prefix=${CMAKE_INSTALL_PREFIX}
includedir=${PKG_CONFIG_INCLUDEDIR}
libdir=${PKG_CONFIG_LIBDIR}
Libs: ${PKG_CONFIG_LIBS}
Cflags: ${PKG_CONFIG_CFLAGS}
