// Generated by CoffeeScript 1.6.2
(function() {
  var Chart, addTimeToData, color, contextHeight, contextWidth, createChart, height, margin, showOnly, svg, width;

  color = d3.scale.category10();

  showOnly = function(chart, b) {
    chart.xScale.domain(b);
    chart.chartContainer.selectAll("rect").data(chart.modes).attr("x", function(d) {
      return chart.xScale(d[0]) + .5;
    }).attr("width", function(d) {
      return chart.xScale(d[1]) - chart.xScale(d[0]) - .5;
    });
    chart.chartContainer.selectAll("line").data(chart.modes).attr("x1", function(d) {
      return chart.xScale(d[0]) + .5;
    }).attr("x2", function(d) {
      return chart.xScale(d[0]) + .5;
    });
    chart.chartContainer.select("path.chart").data([chart.chartData]).attr("d", chart.area);
    chart.chartContainer.select("path.line").data([chart.chartData]).attr("d", chart.line);
    chart.chartContainer.select(".x.axis.top").call(chart.xAxisTop);
    return chart.chartContainer.select(".x.axis.bottom").call(chart.xAxisBottom);
  };

  addTimeToData = function(t, item) {
    item.values = item.values.map(function(data) {
      var ret;

      ret = {};
      ret.time = [+data.time[0] + t[0], +data.time[1] + t[1]];
      ret.enclosure = data.enclosure;
      return ret;
    });
    return item;
  };

  createChart = function(json) {
    var brush, chartHeight, charts, context, contextArea, contextAxis, contextLine, contextXScale, contextYScale, data, data2, groups, i, k, keys, lastTime, maxX, maxY, minX, minY, onBrush, result, s, traces, _i;

    groups = json.groups;
    console.log(groups);
    json.traces = json.traces.slice(1);
    traces = json.traces.filter(function(item) {
      return groups.some(function(g) {
        return (+item[0].group) === g;
      });
    });
    result = [];
    traces.forEach(function(t) {
      return t.forEach(function(item) {
        var k, s, temp;

        temp = item.key.split("_");
        k = temp.slice(0, +(temp.length - 3) + 1 || 9e9).join("_");
        item.key = k;
        item.step = temp[temp.length - 2];
        item.mode = temp[temp.length - 1];
        s = item.step;
        if (!(s in result)) {
          result[s] = new Array();
        }
        if (!(k in result[s])) {
          result[s][k] = new Array();
        }
        return result[s][k] = item;
      });
    });
    lastTime = [];
    data = [];
    result.forEach(function(step_items) {
      var item, k, s, _results;

      _results = [];
      for (k in step_items) {
        item = step_items[k];
        s = +item.step;
        if (!(k in lastTime)) {
          lastTime[k] = [0.0, 0.0];
        }
        result[s][k] = addTimeToData(lastTime[k], item);
        lastTime[k] = result[s][k].values[result[s][k].values.length - 1].time;
        if (!(k in data)) {
          data[k] = result[s][k];
          data[k].modes = [0.0];
        } else {
          data[k].values = data[k].values.concat(result[s][k].values);
        }
        _results.push(data[k].modes.push(lastTime[k][1]));
      }
      return _results;
    });
    charts = [];
    data2 = [];
    for (k in data) {
      s = data[k];
      s.values.forEach(function(d) {
        d.time = [parseFloat(d.time[0]), parseFloat(d.time[1])];
        return d.enclosure = [parseFloat(d.enclosure[0]), parseFloat(d.enclosure[1])];
      });
      s.modes = _.zip(s.modes.slice(0, s.modes.length - 1), s.modes.slice(1));
      data2.push(s);
    }
    data = data2;
    console.log(data2);
    keys = data.length;
    minX = d3.min(data, function(d) {
      return d3.min(d.values, function(p) {
        return p.time[0];
      });
    });
    maxX = d3.max(data, function(d) {
      return d3.max(d.values, function(p) {
        return p.time[1];
      });
    });
    minY = d3.min(data, function(d) {
      return d3.min(d.values, function(p) {
        return p.enclosure[0];
      });
    });
    maxY = d3.max(data, function(d) {
      return d3.max(d.values, function(p) {
        return p.enclosure[1];
      });
    });
    chartHeight = height * (1 / keys);
    contextXScale = d3.scale.linear().range([0, contextWidth]).domain([minX, maxX]);
    contextYScale = d3.scale.linear().range([contextHeight, 0]).domain([minY, maxY]);
    contextAxis = d3.svg.axis().scale(contextXScale).tickSize(contextHeight).tickPadding(-10).orient("bottom");
    contextArea = d3.svg.area().interpolate("monotone").x0(function(p) {
      return contextXScale(p.time[0]);
    }).x1(function(p) {
      return contextXScale(p.time[1]);
    }).y0(function(p) {
      return contextYScale(p.enclosure[0]);
    }).y1(function(p) {
      return contextYScale(p.enclosure[1]);
    });
    contextLine = d3.svg.line().interpolate("monotone").x(function(p) {
      return contextXScale((p.time[0] + p.time[1]) / 2);
    }).y(function(p) {
      return contextYScale((p.enclosure[0] + p.enclosure[1]) / 2);
    });
    context = svg.append("g").attr("class", "context").attr("transform", "translate(" + (0 + margin.left) + "," + (chartHeight * keys + margin.top + margin.bottom) + ")");
    context.append("g").attr("class", "x axis top").attr("transform", "translate(0,0)").call(contextAxis);
    for (i = _i = 0; _i < keys; i = _i += 1) {
      charts.push(new Chart({
        data: data[i].values,
        id: i,
        modes: data[i].modes,
        name: data[i].key,
        width: width,
        height: height * (1 / keys),
        domainX: [minX, maxX],
        svg: svg,
        margin: margin,
        showBottomAxis: true,
        context: context,
        contextArea: contextArea,
        contextLine: contextLine
      }));
    }
    context.append("text").attr("class", "instructions").attr("transform", "translate(0," + (contextHeight + 20) + ")").text('Click and drag above to zoom / pan the data');
    onBrush = function() {
      var b, _j, _results;

      b = brush.empty() ? contextXScale.domain() : brush.extent();
      _results = [];
      for (i = _j = 0; _j < keys; i = _j += 1) {
        _results.push(showOnly(charts[i], b));
      }
      return _results;
    };
    brush = d3.svg.brush().x(contextXScale).on("brush", onBrush);
    return context.append("g").attr("class", "x brush").call(brush).selectAll("rect").attr("y", 0).attr("height", contextHeight);
  };

  Chart = (function() {
    function Chart(options) {
      var maxY, minY, xS, yS;

      this.chartData = options.data;
      this.width = options.width;
      this.height = options.height;
      this.domainX = options.domainX;
      this.modes = options.modes;
      this.svg = options.svg;
      this.id = options.id;
      this.name = options.name;
      this.margin = options.margin;
      this.showBottomAxis = options.showBottomAxis;
      this.xScale = d3.scale.linear().range([0, this.width]).domain(this.domainX);
      minY = d3.min(this.chartData, function(p) {
        return p.enclosure[0];
      });
      maxY = d3.max(this.chartData, function(p) {
        return p.enclosure[1];
      });
      this.yScale = d3.scale.linear().range([this.height, 0]).domain([minY, maxY]);
      xS = this.xScale;
      yS = this.yScale;
      this.line = d3.svg.line().interpolate("basis").x(function(p) {
        return xS((p.time[0] + p.time[1]) / 2);
      }).y(function(p) {
        return yS((p.enclosure[0] + p.enclosure[1]) / 2);
      });
      this.area = d3.svg.area().interpolate("basis").x0(function(p) {
        return xS(p.time[0]);
      }).x1(function(p) {
        return xS(p.time[1]);
      }).y0(function(p) {
        return yS(p.enclosure[0]);
      }).y1(function(p) {
        return yS(p.enclosure[1]);
      });
      this.svg.append("defs").append("clipPath").attr("id", "clip-" + this.id).append("rect").attr("width", this.width).attr("height", this.height);
      this.chartContainer = svg.append("g").attr('class', this.name.toLowerCase()).attr("transform", "translate(" + this.margin.left + "," + (this.margin.top + (this.height * this.id) + (20 * this.id)) + ")");
      this.chartContainer.selectAll("rect").data(this.modes).enter().append("svg:rect").attr("x", function(d) {
        return xS(d[0]) + .5;
      }).attr("y", 0).attr("height", this.height).attr("width", function(d) {
        return xS(d[1]) - xS(d[0]) - .5;
      }).attr("fill", color(this.name)).style("fill-opacity", 0.1).attr("clip-path", "url(#clip-" + this.id + ")");
      this.chartContainer.selectAll("line").data(this.modes).enter().append("svg:line").attr("x1", function(d) {
        return xS(d[1]) + .5;
      }).attr("x2", function(d) {
        return xS(d[1]) + .5;
      }).attr("y1", 0).attr("y2", this.height).style("stroke", "#999999").style("stroke-width", "0.5px").attr("clip-path", "url(#clip-" + this.id + ")");
      this.chartContainer.append("path").data([this.chartData]).attr("class", "chart").attr("clip-path", "url(#clip-" + this.id + ")").attr("d", this.area).style("fill", color(this.name)).style("fill-opacity", 0.8);
      this.chartContainer.append("path").data([this.chartData]).attr("class", "line").attr("clip-path", "url(#clip-" + this.id + ")").attr("d", this.line).style("stroke", color(this.name)).style("stroke-width", "2px").style("fill-opacity", 0.0);
      options.context.append("path").data([this.chartData]).attr("class", "chart").attr("d", options.contextArea).style("fill", "black").style("fill-opacity", 0.1);
      options.context.append("path").data([this.chartData]).attr("d", options.contextLine).style("stroke", color(this.name)).style("stroke-width", "2px").style("fill-opacity", 0.0);
      this.xAxisTop = d3.svg.axis().scale(this.xScale).orient("bottom");
      this.xAxisBottom = d3.svg.axis().scale(this.xScale).orient("bottom");
      if (this.showBottomAxis) {
        this.chartContainer.append("g").attr("class", "x axis bottom").attr("transform", "translate(0," + this.height + ")").call(this.xAxisBottom);
      }
      this.yAxis = d3.svg.axis().scale(this.yScale).orient("left").ticks(5);
      this.chartContainer.append("g").attr("class", "y axis").attr("transform", "translate(0,0)").call(this.yAxis);
      this.chartContainer.append("text").attr("class", "country-title").attr("transform", "translate(15,40)").text(this.name);
    }

    return Chart;

  })();

  margin = {
    top: 10,
    right: 40,
    bottom: 100,
    left: 60
  };

  width = 940 - margin.left - margin.right;

  height = 500 - margin.top - margin.bottom;

  contextHeight = 50;

  contextWidth = width;

  svg = d3.select("#chart-container").append("svg").attr("width", width + margin.left + margin.right).attr("height", height + margin.top + margin.bottom + 200);

  d3.json('data.json', createChart);

}).call(this);
