name: Ubuntu_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * *'

jobs:
  build_test_focal:
    runs-on: ubuntu-20.04
    steps:
     - name: checkout
       uses: actions/checkout@v2
     - name: setup
       run: sudo ./setup/ubuntu/20.04/install_prereqs.sh
     - name: cmake
       run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RELEASE ../src
     - name: make
       run: cd build && make
     - name: test
       run: ./build/dReal src/tests/nra_ode/bouncing_ball_with_drag_10_0.smt2 --model
